version: '{build}'
image: Visual Studio 2017
install:
- ps: >-
    $xmlPath = "$env:appveyor_build_folder\PangLib.IFF\PangLib.IFF.csproj"

    $xml = [xml](get-content $xmlPath)

    $version = ($xml.Project.PropertyGroup | ? {$_.Version}).Version

    Update-AppveyorBuild -Version "$version-$env:appveyor_build_id"
before_build:
- ps: >-
    cd PangLib.IFF/

    dotnet restore
only_commits:
  files:
    - PangLib.IFF/
build:
  project: PangLib.IFF/PangLib.IFF.csproj
  verbosity: minimal