version: '{build}'
image: Visual Studio 2017
install:
- ps: >-
    $xmlPath = "$env:appveyor_build_folder\PangLib.PET\PangLib.PET.csproj"

    $xml = [xml](get-content $xmlPath)

    $version = ($xml.Project.PropertyGroup | ? {$_.Version}).Version

    Update-AppveyorBuild -Version "$version-$env:appveyor_build_id"
before_build:
- ps: >-
    cd PangLib.PET/

    dotnet restore
only_commits:
  files:
    - PangLib.PET/
build:
  project: PangLib.PET/PangLib.PET.csproj
  verbosity: minimal