version: '{build}'
image: Visual Studio 2017
install:
- ps: >-
    $xmlPath = "$env:appveyor_build_folder\PangLib.UpdateList\PangLib.UpdateList.csproj"

    $xml = [xml](get-content $xmlPath)

    $version = ($xml.Project.PropertyGroup | ? {$_.Version}).Version

    Update-AppveyorBuild -Version "$version-$env:appveyor_build_id"
before_build:
- ps: >-
    cd PangLib.UpdateList/

    dotnet restore
only_commits:
  files:
    - PangLib.UpdateList/
build:
  project: PangLib.UpdateList/PangLib.UpdateList.csproj
  verbosity: minimal