version: '{build}'
image: Visual Studio 2017
install:
- ps: >-
    $xmlPath = "$env:appveyor_build_folder\PangLib.Utilities\PangLib.Utilities.csproj"

    $xml = [xml](get-content $xmlPath)

    $version = ($xml.Project.PropertyGroup | ? {$_.Version}).Version

    Update-AppveyorBuild -Version "$version-$env:appveyor_build_id"
before_build:
- ps: >-
    cd PangLib.Utilities/

    dotnet restore
only_commits:
  files:
    - PangLib.Utilities/
build:
  project: PangLib.Utilities/PangLib.Utilities.csproj
  verbosity: minimal